version: "2.1"

services:
  httpserv:
    build:
      dockerfile: Dockerfile
      context: ./httpserv
    ports:
      - "8080:8080"
    volumes:
      - shared-volume:/filefolder

  rapid-runner-rabbit:
      container_name: "rapid-runner-rabbit"
      build:
        dockerfile: Dockerfile
        context: .
      #ports:
      # - 15672:15672
      healthcheck:
        test: ["CMD", "curl", "-f", "http://0.0.0.0:15672"]
        interval: 5s
        timeout: 3s
        retries: 20
  obse:
    restart: on-failure
    depends_on:
      rapid-runner-rabbit:
        condition: service_healthy
    links:
      - rapid-runner-rabbit
    build:
      dockerfile: Dockerfile
      context: ./obse
    volumes:
      - shared-volume:/filefolder

  imed:
    restart: on-failure
    depends_on:
      obse:
        condition: service_started
      rapid-runner-rabbit:
        condition: service_healthy
    links:
      - rapid-runner-rabbit
    build:
      dockerfile: Dockerfile
      context: ./imed
  
  orig:
    build:
      dockerfile: Dockerfile
      context: ./orig
    restart: on-failure
    depends_on:
      obse:
        condition: service_started
      imed:
        condition: service_started
      rapid-runner-rabbit:
        condition: service_healthy
    links:
      - rapid-runner-rabbit

volumes:
  shared-volume: